"""Ascend Triton syntax hooks for the initial SSA emitter tier."""

from dataclasses import dataclass, replace
from typing import Iterable

from ninetoothed.backends.ascend import (
    ASCEND_ELEMENTWISE_DTYPES,
    normalize_ascend_dtype,
    unsupported_ascend_elementwise_dtypes,
)
from ninetoothed.backends.core import Target
from ninetoothed.backends.emitters import ssa as common
from ninetoothed.backends.emitters.analysis import walk_ops
from ninetoothed.backends.emitters.base import ModuleRenderContext
from ninetoothed.backends.emitters.triton import TritonTarget
from ninetoothed.ir import Kernel, ssa

_SUPPORTED_OPCODES = frozenset(
    {
        "arith.add",
        "arith.constant",
        "arith.div",
        "arith.mul",
        "arith.neg",
        "arith.pos",
        "arith.pow",
        "arith.sub",
        "index.offset",
        "linalg.matmul",
        "cmp.eq",
        "cmp.ge",
        "cmp.gt",
        "cmp.le",
        "cmp.lt",
        "cmp.ne",
        "mem.load",
        "mem.store",
        "math.pow",
        "reduce.max",
        "reduce.min",
        "reduce.sum",
        "select.where",
        "scf.for",
        "scf.if",
        "scf.yield",
        "shape.dim",
        "tensor.stride",
        "tensor.empty",
        "tensor.full",
        "tensor.zeros",
        "tensor.cast",
        "tensor.extract",
        "tensor.view",
    }
)


@dataclass(frozen=True, kw_only=True)
class AscendTarget(TritonTarget):
    """Triton Python source accepted by the installed Ascend toolchain."""

    backend: Target = Target.ASCEND
    suffix: str = "ascend.py"
    source_route: str = "ssa-unified-ascend-triton-emitter"
    default_load_mask: bool = False

    def cast(self, dtype: str, value: str) -> str:
        return f"{value}.to(tl.{_triton_dtype(dtype)})"

    def load(self, tensor, index, *, mask=None, other=0.0):
        if mask is None and self.default_load_mask:
            mask = "mask"

        return super().load(tensor, index, mask=mask, other=other)

    def render_module(self, context: ModuleRenderContext) -> str:
        kernel = context.kernel
        body = common.rewrite_index_math(context.body, c_style=False)
        runtime_params = set(kernel.metadata.get("runtime_shape_params", ()))
        params = ",\n    ".join(
            (
                *context.variables,
                *context.outputs,
                *[
                    axis if axis in runtime_params else f"{axis}: tl.constexpr"
                    for axis in context.shape_params
                ],
                "BLOCK: tl.constexpr",
            )
        )
        kernel_args = ",\n        ".join(
            (*context.variables, *context.outputs, *context.shape_params)
        )
        total = context.total
        mask_total = total
        launch_total = total
        launch_grid = f"triton.cdiv({launch_total}, block)"
        offsets_expression = "tl.program_id(0) * BLOCK + tl.arange(0, BLOCK)"
        schedule = kernel.ssa.metadata.get("schedule", {})
        reduction = schedule.get("reduction", {})

        if (
            schedule.get("granularity") == "parallel-reduction"
            and reduction.get("mode") == "row-vector"
        ):
            mask_total = str(reduction.get("extent", total))
            launch_total = context.grid_total
            launch_grid = launch_total
            offsets_expression = "tl.arange(0, BLOCK)"

        result = _output_result(context.outputs)

        return f"""\"\"\"Ascend Triton lowering generated by NineToothed from ssa.Program.

Kernel: {kernel.kernel_name}
Lowering IR: ssa.Program
\"\"\"

import triton
import triton.language as tl
from triton.language.extra.cann import libdevice


@triton.jit
def {kernel.kernel_name}_kernel(
    {params},
):
    offsets = {offsets_expression}
    {self.index_name} = offsets
    mask = offsets < ({mask_total})
{common.indent_block(body, "    ")}

def launch_{kernel.kernel_name}({", ".join((*context.variables, *context.outputs, *context.shape_params))}):
    block = 256
    grid = ({launch_grid},)
    {kernel.kernel_name}_kernel[grid](
        {kernel_args},
        BLOCK=block,
    )
    return {result}
"""


TARGET = AscendTarget()


def emit(kernel: Kernel):
    """Emit only the explicitly verified first Ascend operation tier."""
    _validate_program(kernel)
    schedule = kernel.ssa.metadata.get("schedule", {})
    target = (
        replace(TARGET, default_load_mask=True)
        if schedule.get("granularity") == "blocked-linalg"
        else TARGET
    )

    return common.emit(kernel, target)


def diagnose_opcode_coverage(kernel: Kernel) -> dict[str, tuple[str, ...]]:
    """Return development-only SSA opcode coverage details for an Ascend kernel."""
    if kernel.ssa is None:
        raise ValueError("Ascend opcode diagnostics require ssa.Program.")

    observed = tuple(sorted({op.opcode for op in _operations(kernel.ssa)}))

    return {
        "observed": observed,
        "supported": tuple(
            opcode for opcode in observed if opcode in _SUPPORTED_OPCODES
        ),
        "unsupported": tuple(
            opcode for opcode in observed if opcode not in _SUPPORTED_OPCODES
        ),
    }


def _output_result(outputs: tuple[str, ...]) -> str:
    if not outputs:
        return "None"

    if len(outputs) == 1:
        return outputs[0]

    return f"({', '.join(outputs)})"


def _validate_program(kernel: Kernel) -> None:
    if kernel.ssa is None:
        raise ValueError("Ascend source emission requires ssa.Program.")

    unsupported = sorted(
        {
            op.opcode
            for op in _operations(kernel.ssa)
            if op.opcode not in _SUPPORTED_OPCODES
        }
    )

    if unsupported:
        names = ", ".join(f"`{opcode}`" for opcode in unsupported)
        raise ValueError(
            "Ascend emitter supports only the verified FP16, BF16, and FP32 "
            "elementwise operation "
            f"tier; unsupported SSA opcode(s): {names}."
        )

    unsupported_dtypes = unsupported_ascend_elementwise_dtypes(
        tuple(tensor.dtype for tensor in kernel.tensors if not tensor.constexpr)
    )

    if unsupported_dtypes:
        raise ValueError(
            "Ascend emitter supports only verified FP16, BF16, and FP32 elementwise "
            "dtypes; received tensor dtypes: "
            f"{', '.join(unsupported_dtypes)}."
        )

    schedule = kernel.ssa.metadata.get("schedule", {})

    if schedule.get("granularity") not in {
        "elementwise-grid",
        "parallel-reduction",
        "blocked-linalg",
    }:
        raise ValueError(
            "Ascend emitter requires a verified Ascend schedule; received "
            f"granularity `{schedule.get('granularity')}`."
        )

    if schedule.get("granularity") == "parallel-reduction":
        reduction = schedule.get("reduction", {})

        if reduction.get("mode") != "row-vector":
            raise ValueError(
                "Ascend emitter requires the verified row-vector reduction "
                f"contract; received mode `{reduction.get('mode')}`."
            )

        try:
            extent = int(str(reduction.get("extent")))
        except (TypeError, ValueError):
            extent = None

        if extent is not None and not 0 <= extent <= 256:
            raise ValueError(
                "Ascend emitter supports row-vector reductions with extent at most "
                "BLOCK=256; hierarchical partial reduction is not implemented."
            )

    if schedule.get("granularity") == "blocked-linalg":
        linalg = schedule.get("ascend_linalg", {})

        if linalg.get("mode") != "matrix-scalar-loop":
            raise ValueError(
                "Ascend emitter requires the verified matrix-scalar-loop linalg "
                "contract."
            )

    if schedule.get("tile", {}).get("elements") != 256:
        raise ValueError(
            "Ascend emitter requires the `fp16-bf16-fp32-elementwise-256` "
            "schedule candidate."
        )


def _operations(program: ssa.Program) -> Iterable[ssa.Operation]:
    for block in program.blocks:
        yield from walk_ops(block.operations)


def _triton_dtype(dtype: str) -> str:
    normalized = normalize_ascend_dtype(dtype)

    if normalized not in ASCEND_ELEMENTWISE_DTYPES:
        raise ValueError(f"Unsupported Ascend Triton dtype: {dtype!r}.")

    return normalized


__all__ = ["AscendTarget", "TARGET", "diagnose_opcode_coverage", "emit"]
