"""Ascend Triton syntax hooks for the initial SSA emitter tier."""

from dataclasses import dataclass
from typing import Iterable

from ninetoothed.backends.core import Target
from ninetoothed.backends.emitters import ssa as common
from ninetoothed.backends.emitters.analysis import walk_ops
from ninetoothed.backends.emitters.base import ModuleRenderContext
from ninetoothed.backends.emitters.triton import TritonTarget
from ninetoothed.ir import Kernel, ssa

_SUPPORTED_OPCODES = frozenset(
    {
        "arith.add",
        "arith.constant",
        "arith.div",
        "arith.mul",
        "arith.neg",
        "arith.pos",
        "arith.sub",
        "cmp.eq",
        "cmp.ge",
        "cmp.gt",
        "cmp.le",
        "cmp.lt",
        "cmp.ne",
        "mem.load",
        "mem.store",
        "select.where",
        "tensor.cast",
        "tensor.extract",
    }
)


@dataclass(frozen=True, kw_only=True)
class AscendTarget(TritonTarget):
    """Triton Python source accepted by the installed Ascend toolchain."""

    backend: Target = Target.ASCEND
    suffix: str = "ascend.py"
    source_route: str = "ssa-unified-ascend-triton-emitter"
    contiguous_1d_fast_path: bool = False
    explicit_broadcast_coordinates: bool = True

    def render_module(self, context: ModuleRenderContext) -> str:
        kernel = context.kernel
        body = common.rewrite_index_math(context.body, c_style=False)
        runtime_params = set(kernel.metadata.get("runtime_shape_params", ()))
        params = ",\n    ".join(
            (
                *context.variables,
                *context.outputs,
                *[
                    axis if axis in runtime_params else f"{axis}: tl.constexpr"
                    for axis in context.shape_params
                ],
                "BLOCK: tl.constexpr",
            )
        )
        kernel_args = ",\n        ".join(
            (*context.variables, *context.outputs, *context.shape_params)
        )
        total = context.total
        result = context.outputs[0] if context.outputs else "None"

        return f"""\"\"\"Ascend Triton lowering generated by NineToothed from ssa.Program.

Kernel: {kernel.kernel_name}
Lowering IR: ssa.Program
\"\"\"

import triton
import triton.language as tl
from triton.language.extra.cann import libdevice


@triton.jit
def {kernel.kernel_name}_kernel(
    {params},
):
    offsets = tl.program_id(0) * BLOCK + tl.arange(0, BLOCK)
    {self.index_name} = offsets
    mask = offsets < ({total})
{common.indent_block(body, "    ")}

def launch_{kernel.kernel_name}({", ".join((*context.variables, *context.outputs, *context.shape_params))}):
    block = 256
    grid = (triton.cdiv({total}, block),)
    {kernel.kernel_name}_kernel[grid](
        {kernel_args},
        BLOCK=block,
    )
    return {result}
"""


TARGET = AscendTarget()


def emit(kernel: Kernel):
    """Emit only the explicitly verified first Ascend operation tier."""
    _validate_program(kernel)

    return common.emit(kernel, TARGET)


def _validate_program(kernel: Kernel) -> None:
    if kernel.ssa is None:
        raise ValueError("Ascend source emission requires ssa.Program.")

    unsupported = sorted(
        {
            op.opcode
            for op in _operations(kernel.ssa)
            if op.opcode not in _SUPPORTED_OPCODES
        }
    )

    if unsupported:
        names = ", ".join(f"`{opcode}`" for opcode in unsupported)
        raise ValueError(
            "Ascend emitter supports only the verified FP32 elementwise operation "
            f"tier; unsupported SSA opcode(s): {names}."
        )

    schedule = kernel.ssa.metadata.get("schedule", {})

    if schedule.get("granularity") != "elementwise-grid":
        raise ValueError(
            "Ascend emitter requires the FP32 elementwise schedule; received "
            f"granularity `{schedule.get('granularity')}`."
        )

    if schedule.get("tile", {}).get("elements") != 256:
        raise ValueError(
            "Ascend emitter requires the `fp32-elementwise-256` schedule candidate."
        )


def _operations(program: ssa.Program) -> Iterable[ssa.Operation]:
    for block in program.blocks:
        yield from walk_ops(block.operations)


__all__ = ["AscendTarget", "TARGET", "emit"]
